### ISSUE TITLE
Confirm code of conduct writer

### ISSUE THREAD

**Issue by mcelearr** [FAC8/FAC9-planning#1]
Need to choose one person/people to own this.

**Comment by bradreeder** [comment]
I've just pushed a provisional code of conduct. It builds upon the existing 'rules' section of our gitbook, adding a few things related to pair programming, working together, tardiness, etc, that we all discussed.

My idea in writing it was to express a sense of communal values we're trying to impress through the rules. "don't be late, _so that_ you don't delay others", "clean up after yourself, _so that_ someone else doesn't have to" etc.

Completely happy for it to be binned, or edited/built upon in any way deemed appropriate.

**Comment by bradreeder** [comment]
Me and Sofia have worked on a first draft today. Anyone is free to review it but I guess issue resolved ownership wise.
